set_property PACKAGE_PIN V17 [get_ports {a[0]}]
set_property PACKAGE_PIN V16 [get_ports {a[1]}]
set_property PACKAGE_PIN W16 [get_ports {a[2]}]
set_property PACKAGE_PIN W17 [get_ports {a[3]}]
set_property PACKAGE_PIN W15 [get_ports {a[4]}]
set_property PACKAGE_PIN V15 [get_ports {a[5]}]
set_property PACKAGE_PIN W14 [get_ports {a[6]}]

set_property PACKAGE_PIN W13 [get_ports {b[0]}]
set_property PACKAGE_PIN V2 [get_ports {b[1]}]
set_property PACKAGE_PIN T3 [get_ports {b[2]}]
set_property PACKAGE_PIN T2 [get_ports {b[3]}]
set_property PACKAGE_PIN R3 [get_ports {b[4]}]
set_property PACKAGE_PIN W2 [get_ports {b[5]}]
set_property PACKAGE_PIN U1 [get_ports {b[6]}]

set_property PACKAGE_PIN T1 [get_ports {alu_op[0]}]
set_property PACKAGE_PIN R2 [get_ports {alu_op[1]}]

set_property PACKAGE_PIN W7 [get_ports {result[0]}]
set_property PACKAGE_PIN W6 [get_ports {result[1]}]
set_property PACKAGE_PIN U8 [get_ports {result[2]}]
set_property PACKAGE_PIN V8 [get_ports {result[3]}]
set_property PACKAGE_PIN U5 [get_ports {result[4]}]
set_property PACKAGE_PIN V5 [get_ports {result[5]}]
set_property PACKAGE_PIN U7 [get_ports {result[6]}]

set_property PACKAGE_PIN U16 [get_ports {zero}]

set_property IOSTANDARD LVCMOS33 [get_ports {a b alu_op result zero}]